### ISSUE TITLE
R2dbc H2 does not  work with Spring Boot 2.7 

### ISSUE THREAD

**Issue by hantsy** [spring-projects-experimental/spring-fu#390]
When upgrading my sample project(Spring Fu 0.5.1) to Spring Boot 2.7, I got the following exception.

```bash 
java.lang.NoClassDefFoundError: org/springframework/boot/autoconfigure/r2dbc/EmbeddedDatabaseConnection
```

The details: https://github.com/hantsy/spring-kotlin-dsl-sample/runs/6547991485?check_suite_focus=true

**Comment by sdeleuze** [comment]
That's expected, Spring Fu 0.5 is compatible with Spring Boot 2.6 not 2.7.
