### ISSUE TITLE
Upgrade to Spring Boot 2.6

### ISSUE THREAD

**Issue by hantsy** [spring-projects-experimental/spring-fu#383]
I was using a `0.5-SNAPSHOT` version in my sample projects, but it does not work with the latest Spring Boot 2.6.0-RC1.

Run the application, I got the following exception: 

```bash 
java.lang.NoClassDefFoundError: org/springframework/boot/autoconfigure/web/ResourceProperties
        at org.springframework.fu.jafu.webflux.WebFluxServerDsl.<init>(WebFluxServerDsl.java:59) ~[spring-fu-jafu-0.5.0-SNAPSHOT.jar:na]
        at org.springframework.fu.jafu.webflux.WebFluxServerDsl.webFlux(WebFluxServerDsl.java:81) ~[spring-fu-jafu-0.5.0-SNAPSHOT.jar:na]
        at com.example.demo.Configurations.lambda$static$7(Configurations.java:18) ~[classes/:na]
        at org.springframework.fu.jafu.ConfigurationDsl.initialize(ConfigurationDsl.java:107) ~[spring-fu-jafu-0.5.0-SNAPSHOT.jar:na]
        at org.springframework.fu.jafu.ConfigurationDsl.enable(ConfigurationDsl.java:85) ~[spring-fu-jafu-0.5.0-SNAPSHOT.jar:na]
        at com.example.demo.Application.lambda$static$1(Application.java:14) ~[classes/:na]
        at org.springframework.fu.jafu.ApplicationDsl.initialize(ApplicationDsl.java:27) ~[spring-fu-jafu-0.5.0-SNAPSHOT.jar:na]
        at org.springframework.fu.jafu.ApplicationDsl.initialize(ApplicationDsl.java:15) ~[spring-fu-jafu-0.5.0-SNAPSHOT.jar:na]
        at org.springframework.boot.SpringApplication.applyInitializers(SpringApplication.java:599) ~[spring-boot-2.6.0-RC1.jar:2.6.0-RC1]
        at org.springframework.boot.SpringApplication.prepareContext(SpringApplication.java:367) ~[spring-boot-2.6.0-RC1.jar:2.6.0-RC1]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:301) ~[spring-boot-2.6.0-RC1.jar:2.6.0-RC1]
        at org.springframework.fu.jafu.JafuApplication.run(JafuApplication.java:98) ~[spring-fu-jafu-0.5.0-SNAPSHOT.jar:na]
        at org.springframework.fu.jafu.JafuApplication.run(JafuApplication.java:68) ~[spring-fu-jafu-0.5.0-SNAPSHOT.jar:na]
        at com.example.demo.Application.main(Application.java:18) ~[classes/:na]
```
